In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

In [2]:
df=pd.read_csv("/content/drive/MyDrive/deep learning /glass.csv")

In [3]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
df.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [6]:
from sklearn.preprocessing import LabelEncoder

#Create the object of LabelEncoder class
le=LabelEncoder()
df["Type"]=le.fit_transform(df["Type"])
#check

In [7]:
X=df.drop("Type",axis=1)
Y=df["Type"]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1,stratify=Y)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
ss=StandardScaler()

In [12]:
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [13]:
X_train

array([[-6.15140203e-01, -1.72092416e+00, -1.86395112e+00, ...,
        -1.36240973e-03, -3.57485821e-01, -5.53543774e-01],
       [-6.41179733e-01, -2.86677094e-02,  5.57960430e-01, ...,
        -5.76526386e-01, -3.57485821e-01,  4.59699743e-01],
       [ 1.25319607e+00,  8.69978820e-01,  7.80026818e-01, ...,
         5.12901851e-01, -3.57485821e-01, -5.53543774e-01],
       ...,
       [-1.40934587e+00,  9.63344693e-01,  2.80377445e-01, ...,
        -1.25318989e+00, -3.57485821e-01, -5.53543774e-01],
       [ 3.09263108e-01,  4.26490922e-01, -1.91513630e-01, ...,
         5.67034931e-01, -3.57485821e-01, -5.53543774e-01],
       [-2.96155962e-01, -7.17241024e-01,  6.13477027e-01, ...,
        -2.31428000e-01, -3.57485821e-01, -5.53543774e-01]])

In [14]:
X_test

array([[ 5.04845755e+00, -1.31244847e+00, -1.86395112e+00,
        -8.70435649e-01, -2.94065776e+00, -5.45382276e-01,
         4.91121461e+00, -3.57485821e-01,  1.87824067e+00],
       [-5.92355615e-01, -5.07167809e-01,  3.42833616e-01,
        -4.30727075e-01,  4.53855756e-01,  6.13455474e-02,
        -8.25620299e-02, -3.57485821e-01,  1.87824067e+00],
       [-8.23456443e-01, -6.35545885e-01,  5.16322982e-01,
        -1.05725085e-01,  8.28339454e-01,  2.06432636e-01,
        -5.96826291e-01, -3.57485821e-01,  1.87824067e+00],
       [-4.97962319e-01, -8.80631302e-01,  1.34646377e-01,
         4.86925603e-01,  7.43778619e-01,  2.59191577e-01,
        -2.65261175e-01, -3.57485821e-01, -5.53543774e-01],
       [ 7.77974646e-01,  4.14820188e-01, -2.81728100e-01,
        -4.83717924e-02, -7.29995932e-01, -5.73620703e-02,
         6.21168011e-01, -3.57485821e-01,  1.16897021e+00],
       [-4.26353612e-01,  9.40003225e-01, -1.86395112e+00,
         1.19428288e+00,  9.24980408e-01, -7.036591

In [15]:
model=tf.keras.Sequential([
          tf.keras.layers.Dense(2,activation='relu',input_shape=(X.shape[1],)),
          tf.keras.layers.Dense(3,activation='relu'),
          tf.keras.layers.Dense(3,activation='softmax') #output layer unit of neuron=3              
])

In [18]:
model.compile(optimizer="adam", loss="mse")

In [19]:
trained_model=model.fit(X_train,Y_train,epochs=30, batch_size=10)

Epoch 1/30
15/15 [==============================] - 0s 1ms/step - loss: 4.2456
Epoch 2/30
15/15 [==============================] - 0s 1ms/step - loss: 4.3945
Epoch 3/30
15/15 [==============================] - 0s 1ms/step - loss: 4.6971
Epoch 4/30
15/15 [==============================] - 0s 1ms/step - loss: 3.9905
Epoch 5/30
15/15 [==============================] - 0s 1ms/step - loss: 4.1316
Epoch 6/30
15/15 [==============================] - 0s 1ms/step - loss: 4.1505
Epoch 7/30
15/15 [==============================] - 0s 1ms/step - loss: 4.8339
Epoch 8/30
15/15 [==============================] - 0s 1ms/step - loss: 4.4908
Epoch 9/30
15/15 [==============================] - 0s 1ms/step - loss: 4.4642
Epoch 10/30
15/15 [==============================] - 0s 1ms/step - loss: 3.9185
Epoch 11/30
15/15 [==============================] - 0s 1ms/step - loss: 4.4567
Epoch 12/30
15/15 [==============================] - 0s 2ms/step - loss: 4.5541
Epoch 13/30
15/15 [==============================

In [21]:
Y_pred = model.predict(X_test)

In [22]:
Y_pred

array([[0.32343662, 0.33102232, 0.345541  ],
       [0.336036  , 0.32892388, 0.33504006],
       [0.36090356, 0.34646258, 0.29263383],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.33820453, 0.3294693 , 0.33232617],
       [0.32579976, 0.33064574, 0.34355453],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.33645838, 0.33465102, 0.32889056],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.3566005 , 0.34800118, 0.29539832],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.35094625, 0.3391085 , 0.3099452 ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32343662, 0.33102232, 0.345541  ],
       [0.32795706, 0.330295  , 0.3417479 ],
       [0.33536813, 0.32904068, 0.33559126],
       [0.3311124 , 0.32977027, 0.3391173 ],
       [0.

In [23]:
Y_pred = Y_pred.argmax(axis=1) #select highest probability of multiple class column wise
#and hold in Y_pred
#argmax : inbuilt method ,select highest prob. of multiple class
Y_pred

array([2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2])

In [24]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.29      0.19      0.23        21
           1       0.00      0.00      0.00        23
           2       0.08      0.80      0.14         5
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         9

    accuracy                           0.12        65
   macro avg       0.06      0.17      0.06        65
weighted avg       0.10      0.12      0.08        65



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
